spring:
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: "GMT+8"
  # 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/player_platform
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    path match:
      matching-strategy: ant_path_matcher
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static
mybatis:
  configuration:
    map-underscore-to-camel-case: true
page helper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
