spring:
  devtools:
    restart:
      # ?????
      enabled: true
      # ??????
      additional-paths: src/main/java
      # ??classpath???? WEB-INF ??????????
      exclude: static/**
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: "GMT+8"
  # ???
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/player_platform
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    path match:
      matching-strategy: ant_path_matcher
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    plugins:
      - com.github.pagehelper.PageInterceptor
